export * from './add-instituto-controller-factory'
export * from './add-instituto-validation-factory'
export * from './add-campus-controller-factory'
export * from './add-campus-validation-factory'
export * from './add-diretor-controller-factory'
export * from './add-diretor-validation-factory'
export * from './get-campus-controller-factory'
export * from './get-campus-validation-factory'
export * from './delete-campus-controller-factory'
export * from './delete-campus-validation-factory'
export * from './delete-diretor-controller-factory'
export * from './delete-diretor-validation-factory'

