export * from './add-instituto-factory'
export * from './add-campus-factory'
export * from './get-campus-factory'
export * from './delete-campus-factory'
export * from './add-campus-factory'
export * from './delete-diretor-factory'
