### Variables
@apiurl = http://localhost:3000/api

###
POST {{apiurl}}/institutos
Content-Type: application/json

{
        "razaoSocial": "razaoSocial1",
        "site": "site1",
        "nomeFantasia": "nomeFantasia1",
        "CNPJ": "CNP1J",
        "dataFundacao": "dataFundacao1"

 }

